{{- if and (.Values.nopsAgent) (.Values.nopsAgent.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nops-k8s-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/nops-k8s-agent
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        cert-manager:
        {{- toYaml .Values.nopsAgent | nindent 10 }}
      parameters:
      - name: nops-k8s-agent.serviceAccount.name
        value: {{ .Values.nopsAgent.serviceAccountName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: nops-k8s-agent
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
